server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    location /auth/ {
        proxy_pass http://api-gateway:8080/api/auth/;
    }

    location /users/ {
        proxy_pass http://api-gateway:8080/api/users/;
    }

    location /hospitals/ {
        proxy_pass http://api-gateway:8080/api/hospitals/;
    }

    location /doctors/ {
        proxy_pass http://api-gateway:8080/api/doctors/;
    }

    location /appointments/ {
        proxy_pass http://api-gateway:8080/api/appointments/;
    }

    location /swagger-ui/ {
        proxy_pass http://api-gateway:8080/api/swagger-ui/;
    }

    location /v3/api-docs/ {
        proxy_pass http://api-gateway:8080/api/v3/api-docs/;
    }

    location /actuator/ {
        proxy_pass http://api-gateway:8080/api/actuator/;
    }
}
